"""add user_roles table

Revision ID: 0005
Revises: 0004
Create Date: 2026-08-20 14:21:06.657629

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0005"
down_revision: str | None = "0004"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_roles",
        sa.Column("user_principal_id", sa.UUID(), nullable=False),
        sa.Column("role_principal_id", sa.UUID(), nullable=False),
        sa.Column(
            "assigned_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("assigned_by_principal_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["assigned_by_principal_id"],
            ["iam.principals.id"],
            name=op.f("fk_user_roles_assigned_by_principal_id_principals"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["role_principal_id"],
            ["iam.principals.id"],
            name=op.f("fk_user_roles_role_principal_id_principals"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_principal_id"],
            ["iam.principals.id"],
            name=op.f("fk_user_roles_user_principal_id_principals"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "user_principal_id", "role_principal_id", name=op.f("pk_user_roles")
        ),
        schema="iam",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_roles", schema="iam")
    # ### end Alembic commands ###
