"""add user_identifier table

Revision ID: 0006
Revises: 0005
Create Date: 2026-08-20 14:41:13.252419

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0006"
down_revision: str | None = "0005"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_identifier",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_principal_id", sa.UUID(), nullable=False),
        sa.Column("identifier_type", sa.String(length=100), nullable=False),
        sa.Column("identifier_value", sa.String(length=500), nullable=False),
        sa.Column("normalized_value", sa.String(length=500), nullable=False),
        sa.Column(
            "issuer", sa.String(length=500), server_default=sa.text("'local'"), nullable=False
        ),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("valid_from", sa.DateTime(timezone=True), nullable=True),
        sa.Column("valid_to", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "valid_to IS NULL OR valid_to > valid_from",
            name=op.f("ck_user_identifier_valid_to_after_valid_from"),
        ),
        sa.ForeignKeyConstraint(
            ["user_principal_id"],
            ["iam.users.principal_id"],
            name=op.f("fk_user_identifier_user_principal_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_identifier")),
        schema="iam",
    )
    op.create_index(
        "ix_user_identifiers_user_principal_id",
        "user_identifier",
        ["user_principal_id"],
        unique=False,
        schema="iam",
    )
    op.create_index(
        "uq_user_identifiers_active_identity",
        "user_identifier",
        ["identifier_type", "issuer", "normalized_value"],
        unique=True,
        schema="iam",
        postgresql_where=sa.text("valid_to IS NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_user_identifiers_active_identity",
        table_name="user_identifier",
        schema="iam",
        postgresql_where=sa.text("valid_to IS NULL"),
    )
    op.drop_index(
        "ix_user_identifiers_user_principal_id", table_name="user_identifier", schema="iam"
    )
    op.drop_table("user_identifier", schema="iam")
    # ### end Alembic commands ###
