"""rework user_roles table

Revision ID: 0007
Revises: 0006
Create Date: 2026-08-20 14:50:46.445529

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0007"
down_revision: str | None = "0006"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("pk_user_roles"),
        "user_roles",
        schema="iam",
        type_="primary",
    )
    op.add_column(
        "user_roles",
        sa.Column("id", sa.UUID(), nullable=False, server_default=sa.text("gen_random_uuid()")),
        schema="iam",
    )
    op.alter_column("user_roles", "id", schema="iam", server_default=None)
    op.create_primary_key(op.f("pk_user_roles"), "user_roles", ["id"], schema="iam")
    op.add_column(
        "user_roles",
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        schema="iam",
    )
    op.add_column(
        "user_roles", sa.Column("revoked_by_principal_id", sa.UUID(), nullable=True), schema="iam"
    )
    op.alter_column(
        "user_roles",
        "assigned_by_principal_id",
        existing_type=sa.UUID(),
        nullable=True,
        schema="iam",
    )
    op.create_index(
        "uq_user_roles_active_assignment",
        "user_roles",
        ["user_principal_id", "role_principal_id"],
        unique=True,
        schema="iam",
        postgresql_where=sa.text("revoked_at IS NULL"),
    )
    op.drop_constraint(
        op.f("fk_user_roles_user_principal_id_principals"),
        "user_roles",
        schema="iam",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_user_roles_role_principal_id_principals"),
        "user_roles",
        schema="iam",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_user_roles_assigned_by_principal_id_principals"),
        "user_roles",
        schema="iam",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_user_roles_assigned_by_principal_id_principals"),
        "user_roles",
        "principals",
        ["assigned_by_principal_id"],
        ["id"],
        source_schema="iam",
        referent_schema="iam",
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f("fk_user_roles_role_principal_id_roles"),
        "user_roles",
        "roles",
        ["role_principal_id"],
        ["principal_id"],
        source_schema="iam",
        referent_schema="iam",
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("fk_user_roles_revoked_by_principal_id_principals"),
        "user_roles",
        "principals",
        ["revoked_by_principal_id"],
        ["id"],
        source_schema="iam",
        referent_schema="iam",
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f("fk_user_roles_user_principal_id_users"),
        "user_roles",
        "users",
        ["user_principal_id"],
        ["principal_id"],
        source_schema="iam",
        referent_schema="iam",
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_user_roles_user_principal_id_users"),
        "user_roles",
        schema="iam",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_user_roles_revoked_by_principal_id_principals"),
        "user_roles",
        schema="iam",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_user_roles_role_principal_id_roles"),
        "user_roles",
        schema="iam",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_user_roles_assigned_by_principal_id_principals"),
        "user_roles",
        schema="iam",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_user_roles_assigned_by_principal_id_principals"),
        "user_roles",
        "principals",
        ["assigned_by_principal_id"],
        ["id"],
        source_schema="iam",
        referent_schema="iam",
        ondelete="RESTRICT",
    )
    op.create_foreign_key(
        op.f("fk_user_roles_role_principal_id_principals"),
        "user_roles",
        "principals",
        ["role_principal_id"],
        ["id"],
        source_schema="iam",
        referent_schema="iam",
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("fk_user_roles_user_principal_id_principals"),
        "user_roles",
        "principals",
        ["user_principal_id"],
        ["id"],
        source_schema="iam",
        referent_schema="iam",
        ondelete="CASCADE",
    )
    op.drop_index(
        "uq_user_roles_active_assignment",
        table_name="user_roles",
        schema="iam",
        postgresql_where=sa.text("revoked_at IS NULL"),
    )
    op.alter_column(
        "user_roles",
        "assigned_by_principal_id",
        existing_type=sa.UUID(),
        nullable=False,
        schema="iam",
    )
    op.drop_column("user_roles", "revoked_by_principal_id", schema="iam")
    op.drop_column("user_roles", "revoked_at", schema="iam")
    op.drop_constraint(
        op.f("pk_user_roles"),
        "user_roles",
        schema="iam",
        type_="primary",
    )
    op.drop_column("user_roles", "id", schema="iam")
    op.create_primary_key(
        op.f("pk_user_roles"),
        "user_roles",
        ["user_principal_id", "role_principal_id"],
        schema="iam",
    )
    # ### end Alembic commands ###
