"""narrow roles role_key and add unique constraint

Revision ID: 0008
Revises: 0007
Create Date: 2026-08-20 14:51:52.402834

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0008"
down_revision: str | None = "0007"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "roles",
        "role_key",
        existing_type=sa.VARCHAR(length=255),
        type_=sa.String(length=100),
        existing_nullable=False,
        schema="iam",
    )
    op.create_unique_constraint(op.f("uq_roles_role_key"), "roles", ["role_key"], schema="iam")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_roles_role_key"), "roles", schema="iam", type_="unique")
    op.alter_column(
        "roles",
        "role_key",
        existing_type=sa.String(length=100),
        type_=sa.VARCHAR(length=255),
        existing_nullable=False,
        schema="iam",
    )
    # ### end Alembic commands ###
