"""add ingestion runs and items tables

Revision ID: 0021
Revises: 0020
Create Date: 2026-09-02 18:07:41.936264

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0021"
down_revision: str | None = "0020"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ingestion_runs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "configuration",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("configuration_hash", sa.String(length=64), nullable=False),
        sa.Column("created_by_principal_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by_principal_id"],
            ["iam.principals.id"],
            name=op.f("fk_ingestion_runs_created_by_principal_id_principals"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ingestion_runs")),
        schema="knowledge",
    )
    op.create_table(
        "ingestion_items",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("ingestion_run_id", sa.UUID(), nullable=False),
        sa.Column("document_artifact_id", sa.UUID(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "running",
                "completed",
                "failed",
                name="ingestion_status",
                schema="knowledge",
            ),
            server_default=sa.text("'pending'"),
            nullable=False,
        ),
        sa.Column("attempt_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("claimed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("observed_file_hash", sa.String(length=64), nullable=True),
        sa.Column(
            "execution_metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("error_code", sa.String(length=150), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("activated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deactivated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "activated_at IS NULL OR status = 'completed'",
            name=op.f("ck_ingestion_items_activation_requires_completion"),
        ),
        sa.CheckConstraint(
            "status != 'running'"
            " OR (started_at IS NOT NULL"
            " AND claimed_at IS NOT NULL"
            " AND lease_expires_at IS NOT NULL)",
            name=op.f("ck_ingestion_items_running_requires_claim"),
        ),
        sa.CheckConstraint(
            "status = 'running' OR lease_expires_at IS NULL",
            name=op.f("ck_ingestion_items_lease_only_while_running"),
        ),
        sa.CheckConstraint(
            "status NOT IN ('completed', 'failed') OR completed_at IS NOT NULL",
            name=op.f("ck_ingestion_items_terminal_requires_completed_at"),
        ),
        sa.CheckConstraint(
            "completed_at IS NULL OR (started_at IS NOT NULL AND completed_at >= started_at)",
            name=op.f("ck_ingestion_items_completed_not_before_started"),
        ),
        sa.CheckConstraint(
            "deactivated_at IS NULL"
            " OR (activated_at IS NOT NULL"
            " AND deactivated_at >= activated_at)",
            name=op.f("ck_ingestion_items_deactivation_after_activation"),
        ),
        sa.CheckConstraint(
            "lease_expires_at IS NULL"
            " OR (claimed_at IS NOT NULL"
            " AND lease_expires_at > claimed_at)",
            name=op.f("ck_ingestion_items_valid_lease"),
        ),
        sa.CheckConstraint(
            "attempt_count >= 0", name=op.f("ck_ingestion_items_attempt_count_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["document_artifact_id"],
            ["knowledge.document_artifacts.id"],
            name=op.f("fk_ingestion_items_document_artifact_id_document_artifacts"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["ingestion_run_id"],
            ["knowledge.ingestion_runs.id"],
            name=op.f("fk_ingestion_items_ingestion_run_id_ingestion_runs"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ingestion_items")),
        sa.UniqueConstraint(
            "ingestion_run_id", "document_artifact_id", name="uq_ingestion_items_run_artifact"
        ),
        schema="knowledge",
    )
    op.create_index(
        "ix_ingestion_items_document_artifact_id",
        "ingestion_items",
        ["document_artifact_id"],
        unique=False,
        schema="knowledge",
    )
    op.create_index(
        "ix_ingestion_items_expired_running_lease",
        "ingestion_items",
        ["lease_expires_at"],
        unique=False,
        schema="knowledge",
        postgresql_where=sa.text("status = 'running'"),
    )
    op.create_index(
        "ix_ingestion_items_status", "ingestion_items", ["status"], unique=False, schema="knowledge"
    )
    op.create_index(
        "uq_ingestion_items_active_artifact",
        "ingestion_items",
        ["document_artifact_id"],
        unique=True,
        schema="knowledge",
        postgresql_where=sa.text("activated_at IS NOT NULL AND deactivated_at IS NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_ingestion_items_active_artifact",
        table_name="ingestion_items",
        schema="knowledge",
        postgresql_where=sa.text("activated_at IS NOT NULL AND deactivated_at IS NULL"),
    )
    op.drop_index("ix_ingestion_items_status", table_name="ingestion_items", schema="knowledge")
    op.drop_index(
        "ix_ingestion_items_expired_running_lease",
        table_name="ingestion_items",
        schema="knowledge",
        postgresql_where=sa.text("status = 'running'"),
    )
    op.drop_index(
        "ix_ingestion_items_document_artifact_id", table_name="ingestion_items", schema="knowledge"
    )
    op.drop_table("ingestion_items", schema="knowledge")
    op.drop_table("ingestion_runs", schema="knowledge")
    sa.Enum(name="ingestion_status", schema="knowledge").drop(op.get_bind())
    # ### end Alembic commands ###
