"""add identity tables

Revision ID: 22b0753d075d
Revises: c525fcb7c817
Create Date: 2026-08-20 13:28:01.418805

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "22b0753d075d"
down_revision: str | None = "c525fcb7c817"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE SCHEMA IF NOT EXISTS iam")
    op.create_table(
        "principals",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "type",
            sa.Enum("user", "role", "group", name="principal_type", schema="iam"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column(
            "status_changed_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.CheckConstraint(
            "deleted_at IS NULL OR is_active = false",
            name=op.f("ck_principals_deleted_principal_inactive"),
        ),
        sa.CheckConstraint(
            "status_changed_at >= created_at",
            name=op.f("ck_principals_status_changed_not_before_created"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_principals")),
        sa.UniqueConstraint("id", "type", name="id_type"),
        schema="iam",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("principals", schema="iam")
    principal_type = sa.Enum(
        "user",
        "role",
        "group",
        name="principal_type",
        schema="iam",
    )
    principal_type.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
